// <auto-generated />
namespace CloudDeploy.Persistence.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class cloudmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cloudmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201302230459569_cloud.model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
